# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/price_comparator
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# Puerto
server.port=8080

# Nombre de la app
spring.application.name=price-comparator

springdoc.swagger-ui.path=/swagger-ui.html